// GENERATED by tools/wf2rn/build_all.sh
import type { ComponentType } from 'react';

import WF_C2 from './C2';
import WF_E2w from './E2w';
import WF_P0 from './P0';
import WF_P0b from './P0b';
import WF_P1 from './P1';
import WF_P10 from './P10';
import WF_P10b from './P10b';
import WF_P11 from './P11';
import WF_P11b from './P11b';
import WF_P12 from './P12';
import WF_P12b from './P12b';
import WF_P18 from './P18';
import WF_P18e from './P18e';
import WF_P19 from './P19';
import WF_P19e from './P19e';
import WF_P2 from './P2';
import WF_P20 from './P20';
import WF_P20a from './P20a';
import WF_P20b from './P20b';
import WF_P20c from './P20c';
import WF_P20d from './P20d';
import WF_P20e from './P20e';
import WF_P20f from './P20f';
import WF_P20g from './P20g';
import WF_P21 from './P21';
import WF_P21b from './P21b';
import WF_P22 from './P22';
import WF_P22b from './P22b';
import WF_P23 from './P23';
import WF_P24 from './P24';
import WF_P25 from './P25';
import WF_P26 from './P26';
import WF_P27 from './P27';
import WF_P27b from './P27b';
import WF_P28 from './P28';
import WF_P29 from './P29';
import WF_P3 from './P3';
import WF_P30 from './P30';
import WF_P31 from './P31';
import WF_P32 from './P32';
import WF_P32b from './P32b';
import WF_P3b from './P3b';
import WF_P3c from './P3c';
import WF_P4 from './P4';
import WF_P4a from './P4a';
import WF_P4b from './P4b';
import WF_P4c from './P4c';
import WF_P4d from './P4d';
import WF_P4e from './P4e';
import WF_P4g from './P4g';
import WF_P4h from './P4h';
import WF_P4i from './P4i';
import WF_P4j from './P4j';
import WF_P4k from './P4k';
import WF_P5 from './P5';
import WF_P54 from './P54';
import WF_P54b from './P54b';
import WF_P55 from './P55';
import WF_P56 from './P56';
import WF_P56b from './P56b';
import WF_P57 from './P57';
import WF_P57b from './P57b';
import WF_P57c from './P57c';
import WF_P57d from './P57d';
import WF_P58 from './P58';
import WF_P58b from './P58b';
import WF_P5b from './P5b';
import WF_P6a from './P6a';
import WF_P6b from './P6b';
import WF_P6c from './P6c';
import WF_P7 from './P7';
import WF_P74 from './P74';
import WF_P74b from './P74b';
import WF_P75 from './P75';
import WF_P76 from './P76';
import WF_P76b from './P76b';
import WF_P77 from './P77';
import WF_P7a from './P7a';
import WF_P7b from './P7b';
import WF_P8 from './P8';
import WF_P8b from './P8b';
import WF_P9 from './P9';
import WF_P9t from './P9t';
import WF_S1 from './S1';
import WF_S10 from './S10';
import WF_S11 from './S11';
import WF_S11b from './S11b';
import WF_S12 from './S12';
import WF_S13 from './S13';
import WF_S13b from './S13b';
import WF_S14 from './S14';
import WF_S14b from './S14b';
import WF_S15 from './S15';
import WF_S15b from './S15b';
import WF_S15c from './S15c';
import WF_S16 from './S16';
import WF_S17 from './S17';
import WF_S17b from './S17b';
import WF_S17c from './S17c';
import WF_S18 from './S18';
import WF_S19 from './S19';
import WF_S2 from './S2';
import WF_S21 from './S21';
import WF_S22 from './S22';
import WF_S22b from './S22b';
import WF_S22c from './S22c';
import WF_S22d from './S22d';
import WF_S24 from './S24';
import WF_S25 from './S25';
import WF_S26 from './S26';
import WF_S27 from './S27';
import WF_S27b from './S27b';
import WF_S27c from './S27c';
import WF_S2a from './S2a';
import WF_S3 from './S3';
import WF_S37 from './S37';
import WF_S37b from './S37b';
import WF_S39 from './S39';
import WF_S3b from './S3b';
import WF_S3d from './S3d';
import WF_S3e from './S3e';
import WF_S4 from './S4';
import WF_S40 from './S40';
import WF_S41 from './S41';
import WF_S41b from './S41b';
import WF_S42 from './S42';
import WF_S43 from './S43';
import WF_S44 from './S44';
import WF_S45 from './S45';
import WF_S48 from './S48';
import WF_S4t from './S4t';
import WF_S5 from './S5';
import WF_S50 from './S50';
import WF_S51 from './S51';
import WF_S6 from './S6';
import WF_S6a from './S6a';
import WF_S6c from './S6c';
import WF_S7 from './S7';
import WF_S7b from './S7b';
import WF_S7c from './S7c';
import WF_S8 from './S8';
import WF_S8b from './S8b';
import WF_S9 from './S9';

export const WIREFRAMES: Record<string, ComponentType> = {
  C2: WF_C2,
  E2w: WF_E2w,
  P0: WF_P0,
  P0b: WF_P0b,
  P1: WF_P1,
  P10: WF_P10,
  P10b: WF_P10b,
  P11: WF_P11,
  P11b: WF_P11b,
  P12: WF_P12,
  P12b: WF_P12b,
  P18: WF_P18,
  P18e: WF_P18e,
  P19: WF_P19,
  P19e: WF_P19e,
  P2: WF_P2,
  P20: WF_P20,
  P20a: WF_P20a,
  P20b: WF_P20b,
  P20c: WF_P20c,
  P20d: WF_P20d,
  P20e: WF_P20e,
  P20f: WF_P20f,
  P20g: WF_P20g,
  P21: WF_P21,
  P21b: WF_P21b,
  P22: WF_P22,
  P22b: WF_P22b,
  P23: WF_P23,
  P24: WF_P24,
  P25: WF_P25,
  P26: WF_P26,
  P27: WF_P27,
  P27b: WF_P27b,
  P28: WF_P28,
  P29: WF_P29,
  P3: WF_P3,
  P30: WF_P30,
  P31: WF_P31,
  P32: WF_P32,
  P32b: WF_P32b,
  P3b: WF_P3b,
  P3c: WF_P3c,
  P4: WF_P4,
  P4a: WF_P4a,
  P4b: WF_P4b,
  P4c: WF_P4c,
  P4d: WF_P4d,
  P4e: WF_P4e,
  P4g: WF_P4g,
  P4h: WF_P4h,
  P4i: WF_P4i,
  P4j: WF_P4j,
  P4k: WF_P4k,
  P5: WF_P5,
  P54: WF_P54,
  P54b: WF_P54b,
  P55: WF_P55,
  P56: WF_P56,
  P56b: WF_P56b,
  P57: WF_P57,
  P57b: WF_P57b,
  P57c: WF_P57c,
  P57d: WF_P57d,
  P58: WF_P58,
  P58b: WF_P58b,
  P5b: WF_P5b,
  P6a: WF_P6a,
  P6b: WF_P6b,
  P6c: WF_P6c,
  P7: WF_P7,
  P74: WF_P74,
  P74b: WF_P74b,
  P75: WF_P75,
  P76: WF_P76,
  P76b: WF_P76b,
  P77: WF_P77,
  P7a: WF_P7a,
  P7b: WF_P7b,
  P8: WF_P8,
  P8b: WF_P8b,
  P9: WF_P9,
  P9t: WF_P9t,
  S1: WF_S1,
  S10: WF_S10,
  S11: WF_S11,
  S11b: WF_S11b,
  S12: WF_S12,
  S13: WF_S13,
  S13b: WF_S13b,
  S14: WF_S14,
  S14b: WF_S14b,
  S15: WF_S15,
  S15b: WF_S15b,
  S15c: WF_S15c,
  S16: WF_S16,
  S17: WF_S17,
  S17b: WF_S17b,
  S17c: WF_S17c,
  S18: WF_S18,
  S19: WF_S19,
  S2: WF_S2,
  S21: WF_S21,
  S22: WF_S22,
  S22b: WF_S22b,
  S22c: WF_S22c,
  S22d: WF_S22d,
  S24: WF_S24,
  S25: WF_S25,
  S26: WF_S26,
  S27: WF_S27,
  S27b: WF_S27b,
  S27c: WF_S27c,
  S2a: WF_S2a,
  S3: WF_S3,
  S37: WF_S37,
  S37b: WF_S37b,
  S39: WF_S39,
  S3b: WF_S3b,
  S3d: WF_S3d,
  S3e: WF_S3e,
  S4: WF_S4,
  S40: WF_S40,
  S41: WF_S41,
  S41b: WF_S41b,
  S42: WF_S42,
  S43: WF_S43,
  S44: WF_S44,
  S45: WF_S45,
  S48: WF_S48,
  S4t: WF_S4t,
  S5: WF_S5,
  S50: WF_S50,
  S51: WF_S51,
  S6: WF_S6,
  S6a: WF_S6a,
  S6c: WF_S6c,
  S7: WF_S7,
  S7b: WF_S7b,
  S7c: WF_S7c,
  S8: WF_S8,
  S8b: WF_S8b,
  S9: WF_S9,
};
