// GENERATED by tools/wf2rn/build_all.sh
import type { ComponentType } from 'react';
import WF_P0 from './P0';
import WF_P0b from './P0b';
import WF_P1 from './P1';
import WF_P10 from './P10';
import WF_P10b from './P10b';
import WF_P12 from './P12';
import WF_P12b from './P12b';
import WF_P18 from './P18';
import WF_P18e from './P18e';
import WF_P19 from './P19';
import WF_P19e from './P19e';
import WF_P20 from './P20';
import WF_P20a from './P20a';
import WF_P20b from './P20b';
import WF_P20c from './P20c';
import WF_P20d from './P20d';
import WF_P20e from './P20e';
import WF_P20f from './P20f';
import WF_P20g from './P20g';
import WF_P23 from './P23';
import WF_P24 from './P24';
import WF_P25 from './P25';
import WF_P26 from './P26';
import WF_P3 from './P3';
import WF_P3b from './P3b';
import WF_P4 from './P4';
import WF_P4a from './P4a';
import WF_P4b from './P4b';
import WF_P4c from './P4c';
import WF_P4d from './P4d';
import WF_P4e from './P4e';
import WF_P4g from './P4g';
import WF_P4h from './P4h';
import WF_P4i from './P4i';
import WF_P4j from './P4j';
import WF_P5 from './P5';
import WF_P54 from './P54';
import WF_P54b from './P54b';
import WF_P55 from './P55';
import WF_P56 from './P56';
import WF_P57 from './P57';
import WF_P58 from './P58';
import WF_P5b from './P5b';
import WF_P6a from './P6a';
import WF_P6b from './P6b';
import WF_P6c from './P6c';
import WF_P7 from './P7';
import WF_P74 from './P74';
import WF_P74b from './P74b';
import WF_P75 from './P75';
import WF_P76 from './P76';
import WF_P76b from './P76b';
import WF_P9 from './P9';
import WF_S1 from './S1';
import WF_S10 from './S10';
import WF_S11 from './S11';
import WF_S11b from './S11b';
import WF_S2 from './S2';
import WF_S21 from './S21';
import WF_S24 from './S24';
import WF_S25 from './S25';
import WF_S2a from './S2a';
import WF_S3 from './S3';
import WF_S37 from './S37';
import WF_S37b from './S37b';
import WF_S39 from './S39';
import WF_S3b from './S3b';
import WF_S3d from './S3d';
import WF_S3e from './S3e';
import WF_S4 from './S4';
import WF_S42 from './S42';
import WF_S43 from './S43';
import WF_S44 from './S44';
import WF_S45 from './S45';
import WF_S48 from './S48';
import WF_S5 from './S5';
import WF_S50 from './S50';
import WF_S51 from './S51';
import WF_S6 from './S6';
import WF_S6a from './S6a';
import WF_S6c from './S6c';
import WF_S9 from './S9';
import WF_S8 from './S8';
import WF_P8 from './P8';
import WF_C2 from './C2';
import WF_S22 from './S22';

export const WIREFRAMES: Record<string, ComponentType> = {
  P0: WF_P0,
  P0b: WF_P0b,
  P1: WF_P1,
  P10: WF_P10,
  P10b: WF_P10b,
  P12: WF_P12,
  P12b: WF_P12b,
  P18: WF_P18,
  P18e: WF_P18e,
  P19: WF_P19,
  P19e: WF_P19e,
  P20: WF_P20,
  P20a: WF_P20a,
  P20b: WF_P20b,
  P20c: WF_P20c,
  P20d: WF_P20d,
  P20e: WF_P20e,
  P20f: WF_P20f,
  P20g: WF_P20g,
  P23: WF_P23,
  P24: WF_P24,
  P25: WF_P25,
  P26: WF_P26,
  P3: WF_P3,
  P3b: WF_P3b,
  P4: WF_P4,
  P4a: WF_P4a,
  P4b: WF_P4b,
  P4c: WF_P4c,
  P4d: WF_P4d,
  P4e: WF_P4e,
  P4g: WF_P4g,
  P4h: WF_P4h,
  P4i: WF_P4i,
  P4j: WF_P4j,
  P5: WF_P5,
  P54: WF_P54,
  P54b: WF_P54b,
  P55: WF_P55,
  P56: WF_P56,
  P57: WF_P57,
  P58: WF_P58,
  P5b: WF_P5b,
  P6a: WF_P6a,
  P6b: WF_P6b,
  P6c: WF_P6c,
  P7: WF_P7,
  P74: WF_P74,
  P74b: WF_P74b,
  P75: WF_P75,
  P76: WF_P76,
  P76b: WF_P76b,
  P9: WF_P9,
  S1: WF_S1,
  S10: WF_S10,
  S11: WF_S11,
  S11b: WF_S11b,
  S2: WF_S2,
  S21: WF_S21,
  S24: WF_S24,
  S25: WF_S25,
  S2a: WF_S2a,
  S3: WF_S3,
  S37: WF_S37,
  S37b: WF_S37b,
  S39: WF_S39,
  S3b: WF_S3b,
  S3d: WF_S3d,
  S3e: WF_S3e,
  S4: WF_S4,
  S42: WF_S42,
  S43: WF_S43,
  S44: WF_S44,
  S45: WF_S45,
  S48: WF_S48,
  S5: WF_S5,
  S50: WF_S50,
  S51: WF_S51,
  S6: WF_S6,
  S6a: WF_S6a,
  S6c: WF_S6c,
  S9: WF_S9,
  S8: WF_S8,
  P8: WF_P8,
  C2: WF_C2,
  S22: WF_S22,
};
