#!/usr/bin/env bash
# Regenerate app/src/wireframes/*.tsx from the wireframe HTML, plus the index the dev route uses.
# Usage: tools/wf2rn/build_all.sh <wireframes dir> ID-Name [ID-Name ...]
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd); app="$here/../../app"; src=$1; shift
out="$app/src/wireframes"; mkdir -p "$out"
idx="$out/index.ts"; echo "// GENERATED by tools/wf2rn/build_all.sh" > "$idx"; echo "import type { ComponentType } from 'react';" >> "$idx"; echo >> "$idx"
names=()
for w in "$@"; do id=${w%%-*}; python3 "$here/convert.py" "$src/$w.dc.html" "$out/$id.tsx" "WF_$id" >/dev/null; echo "import WF_$id from './$id';" >> "$idx"; names+=("$id"); done
echo >> "$idx"; echo "export const WIREFRAMES: Record<string, ComponentType> = {" >> "$idx"
for id in "${names[@]}"; do echo "  $id: WF_$id," >> "$idx"; done
echo "};" >> "$idx"
echo "generated ${#names[@]} screens"
